/**
 *  @file   LArRecoND/include/LArSP.h
 *
 *  @brief  Header file defining the "SpacePoint" (SP) format.
 *          Based on autogenerated ROOT code with Pandora-style edits
 *
 *  $Log: $
 */
#ifndef PANDORA_LAR_SP_H
#define PANDORA_LAR_SP_H 1

#include "TChain.h"
#include "TFile.h"
#include "TROOT.h"

// Header file for the classes stored in the TTree if any.
#include <vector>

namespace lar_nd_reco
{

class LArSP
{
public:
    /**
     *  @brief  Constructor requiring TTree pointer
     *
     *  @param  tree The TTree pointer
     */
    LArSP(TTree *tree = nullptr);

    /**
     *  @brief  Destructor
     */
    virtual ~LArSP();

    /**
     *  @brief  Get the corresponding data entry
     *
     *  @param  entry The entry integer index
     *
     *  @return Total number of bytes read
     */
    virtual Int_t GetEntry(Long64_t entry);

    /**
     *  @brief  Initialise using the input TTree
     *
     *  @param  tree The input TTree
     */
    virtual void Init(TTree *tree);

    TTree *m_fChain;  ///< pointer to the analyzed TTree or TChain
    Int_t m_fCurrent; ///< current Tree number in a TChain

    // Declaration of leaf types
    Int_t m_event;
    Int_t m_subrun;
    Int_t m_run;
    Int_t m_event_start_t;
    Int_t m_event_end_t;
    std::vector<float> *m_x = nullptr;
    std::vector<float> *m_y = nullptr;
    std::vector<float> *m_z = nullptr;
    std::vector<float> *m_ts = nullptr;
    std::vector<float> *m_charge = nullptr;
    std::vector<float> *m_E = nullptr;

    // List of branches
    TBranch *m_b_eventID = nullptr;
    TBranch *m_b_subrun = nullptr;
    TBranch *m_b_run = nullptr;
    TBranch *m_b_event_start_t = nullptr;
    TBranch *m_b_event_end_t = nullptr;
    TBranch *m_b_x = nullptr;
    TBranch *m_b_y = nullptr;
    TBranch *m_b_z = nullptr;
    TBranch *m_b_ts = nullptr;
    TBranch *m_b_charge = nullptr;
    TBranch *m_b_E = nullptr;
};

//------------------------------------------------------------------------------------------------------------------------------------------

LArSP::LArSP(TTree *tree) : m_fChain(nullptr)
{
    // if parameter tree is not specified (or zero), connect the file
    // used to generate this class and read the Tree.
    if (tree == nullptr)
    {
        TFile *f = dynamic_cast<TFile *>(gROOT->GetListOfFiles()->FindObject("MiniRun3_1E19_RHC.flow_v3.00000.FLOWunMergedhits_withTruth.root"));
        if (!f || !f->IsOpen())
        {
            f = new TFile("MiniRun3_1E19_RHC.flow_v3.00000.FLOWunMergedhits_withTruth.root");
        }
        f->GetObject("events", tree);
    }
    Init(tree);
}

//------------------------------------------------------------------------------------------------------------------------------------------

LArSP::~LArSP()
{
    if (!m_fChain)
        return;
    delete m_fChain->GetCurrentFile();
}

//------------------------------------------------------------------------------------------------------------------------------------------

Int_t LArSP::GetEntry(Long64_t entry)
{
    // Read contents of entry.
    if (!m_fChain)
        return 0;
    return m_fChain->GetEntry(entry);
}

//------------------------------------------------------------------------------------------------------------------------------------------

void LArSP::Init(TTree *tree)
{
    // The Init() function is called when the selector needs to initialize
    // a new tree or chain. Typically here the branch addresses and branch
    // pointers of the tree will be set.
    // It is normally not necessary to make changes to the generated
    // code, but the routine can be extended by the user if needed.
    // Init() will be called many times when running on PROOF
    // (once per file to be processed).

    // Set branch addresses and branch pointers
    if (!tree)
        return;
    m_fChain = tree;
    m_fCurrent = -1;
    m_fChain->SetMakeClass(1);

    m_fChain->SetBranchAddress("event", &m_event, &m_b_eventID);
    m_fChain->SetBranchAddress("subrun", &m_subrun, &m_b_subrun);
    m_fChain->SetBranchAddress("run", &m_run, &m_b_run);
    m_fChain->SetBranchAddress("event_start_t", &m_event_start_t, &m_b_event_start_t);
    m_fChain->SetBranchAddress("event_end_t", &m_event_end_t, &m_b_event_end_t);
    m_fChain->SetBranchAddress("x", &m_x, &m_b_x);
    m_fChain->SetBranchAddress("y", &m_y, &m_b_y);
    m_fChain->SetBranchAddress("z", &m_z, &m_b_z);
    m_fChain->SetBranchAddress("ts", &m_ts, &m_b_ts);
    m_fChain->SetBranchAddress("charge", &m_charge, &m_b_charge);
    m_fChain->SetBranchAddress("E", &m_E, &m_b_E);
}

} // end namespace lar_nd_reco

#endif
